name: litertlm
description: Unified Flutter package for LiteRT-LM on every platform.
version: 0.0.1
homepage:

environment:
  sdk: ^3.12.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
